#define BUILD_COMMIT_ID "4.0.0"
#define PROJECT_VERSION "1.0.2"
#define PROJECT_VERSION_BUILD_NO "1256"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
